const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },{
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },{
        src:'./images/kurly_003.jpg',
        name:'[오뚜기] 진라면 매운맛 (5개입)',
        summary:'칼칼한 국물 맛의 국민 라면',
        price:3480,
        sale:10,
        review:2456,
    },{
        src:'./images/kurly_004.jpg',
        name:'[매일] 멸균우유 200ml x 24팩',
        summary:'언제 어디서나 간편하게 즐기는 우유',
        price:11800,
        sale:15,
        review:812,
    },{
        src:'./images/kurly_005.jpg',
        name:'[프레시지] 밀푀유나베 2~3인분',
        summary:'간편하게 즐기는 정통 일본식 전골',
        price:13800,
        sale:20,
        review:356,
    },{
        src:'./images/kurly_006.jpg',
        name:'[곰곰] 냉동 블루베리 1kg',
        summary:'상큼달콤한 냉동 과일',
        price:7200,
        sale:12,
        review:104,
    },{
        src:'./images/kurly_007.jpg',
        name:'[풀무원] 얄피꽉찬 만두 2종 (2개입) (택1)',
        summary:'2개입으로 즐기는 풍성한 만두',
        price:7980,
        sale:25,
        review:502,
    },{
        src:'./images/kurly_008.jpg',
        name:'[마켓컬리 단독] 버터갈릭 새우볶음밥 300g',
        summary:'고소한 마늘버터향 가득',
        price:3900,
        sale:18,
        review:78,
    },{
        src:'./images/kurly_009.jpg',
        name:'[CJ] 비비고 왕교자 1.05kg',
        summary:'속이 꽉 찬 정통 교자만두',
        price:8490,
        sale:10,
        review:1350,
    },{
        src:'./images/kurly_010.jpg',
        name:'[대상] 종가집 포기김치 3kg',
        summary:'국내산 재료로 만든 전통 김치',
        price:16800,
        sale:5,
        review:294,
    },{
        src:'./images/kurly_011.jpg',
        name:'[폴 바셋] 콜드브루 원액 300mL',
        summary:'카페 퀄리티의 진한 커피 원액',
        price:9800,
        sale:22,
        review:115,
    },{
        src:'./images/kurly_012.jpg',
        name:'[빙그레] 바나나맛우유 240ml x 4입',
        summary:'국민 간식 바나나맛 우유',
        price:3480,
        sale:8,
        review:907,
    }    
]